#!/usr/bin/env node
/**
 * Generates language bindings for the balance constants.
 *
 * Constitution Principle I requires balance changes to have exactly one edit site.
 * Because the backend is C# and the frontend is TypeScript, they cannot share a literal
 * source file, so both are generated from shared/balance-constants.json instead.
 *
 * Outputs (never hand-edit, both gitignored):
 *   backend/src/MatchServer/Generated/BalanceConstants.cs
 *   frontend/src/generated/balanceConstants.ts
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..', '..');
const SOURCE = path.join(ROOT, 'shared', 'balance-constants.json');
const CS_OUT = path.join(ROOT, 'backend', 'src', 'MatchServer', 'Generated', 'BalanceConstants.cs');
const TS_OUT = path.join(ROOT, 'frontend', 'src', 'generated', 'balanceConstants.ts');

const BANNER = [
  '// <auto-generated>',
  '//   Generated from shared/balance-constants.json by shared/codegen/generate.js.',
  '//   DO NOT EDIT BY HAND - changes here are overwritten on the next build.',
  '//   To change a balance value, edit shared/balance-constants.json and regenerate',
  '//   (Constitution Principle I: balance changes update one place, not two).',
  '// </auto-generated>',
].join('\n');

/** Drop the $comment / $spec provenance keys - they document the JSON, not the bindings. */
const isMeta = (key) => key.startsWith('$');

const pascal = (s) => s.charAt(0).toUpperCase() + s.slice(1);

/**
 * JSON.parse collapses 1.0 to the integer 1, which would emit `const int PacmanBaseSpeed = 1`
 * and turn every speed multiplication into integer math. Recover the author's intent by
 * scanning the raw source for keys written with a decimal point, and treat those as doubles
 * even when the parsed value happens to be whole.
 */
function findDecimalKeys(rawJson) {
  const keys = new Set();
  const scalar = /"([A-Za-z][\w]*)"\s*:\s*-?\d+\.\d+/g;
  const array = /"([A-Za-z][\w]*)"\s*:\s*\[([^\]]*)\]/g;
  let m;
  while ((m = scalar.exec(rawJson)) !== null) keys.add(m[1]);
  while ((m = array.exec(rawJson)) !== null) {
    if (/\d+\.\d+/.test(m[2])) keys.add(m[1]);
  }
  return keys;
}

let decimalKeys = new Set();
const isDouble = (key, value) => !Number.isInteger(value) || decimalKeys.has(key);

/** C# literal. Doubles get a `d` suffix so 1.0 does not silently become an int. */
function csLiteral(key, value) {
  if (typeof value !== 'number') {
    throw new Error(`unsupported scalar: ${JSON.stringify(value)}`);
  }
  if (!isDouble(key, value)) return String(value);
  return Number.isInteger(value) ? `${value}.0d` : `${value}d`;
}

function generateCSharp(data) {
  const lines = [
    BANNER,
    '',
    'namespace MatchServer.Generated;',
    '',
    '/// <summary>Spec-derived balance constants. See shared/balance-constants.json for provenance.</summary>',
    'public static class BalanceConstants',
    '{',
  ];

  for (const [group, entries] of Object.entries(data)) {
    if (isMeta(group)) continue;
    const spec = entries.$spec;
    lines.push(`    /// <summary>${spec ?? group}</summary>`);
    lines.push(`    public static class ${pascal(group)}`);
    lines.push('    {');
    for (const [key, value] of Object.entries(entries)) {
      if (isMeta(key)) continue;
      if (Array.isArray(value)) {
        const elemType = value.some((v) => isDouble(key, v)) ? 'double' : 'int';
        const elems = value.map((v) => csLiteral(key, v)).join(', ');
        lines.push(`        public static readonly ${elemType}[] ${pascal(key)} = { ${elems} };`);
      } else {
        const type = isDouble(key, value) ? 'double' : 'int';
        lines.push(`        public const ${type} ${pascal(key)} = ${csLiteral(key, value)};`);
      }
    }
    lines.push('    }');
    lines.push('');
  }

  lines.push('}');
  return lines.join('\n') + '\n';
}

function generateTypeScript(data) {
  const lines = [BANNER, ''];

  for (const [group, entries] of Object.entries(data)) {
    if (isMeta(group)) continue;
    const spec = entries.$spec;
    if (spec) lines.push(`/** ${spec} */`);
    lines.push(`export const ${group} = {`);
    for (const [key, value] of Object.entries(entries)) {
      if (isMeta(key)) continue;
      lines.push(`  ${key}: ${JSON.stringify(value)},`);
    }
    lines.push('} as const;');
    lines.push('');
  }

  const groups = Object.keys(data).filter((k) => !isMeta(k));
  lines.push('export const balanceConstants = {');
  for (const g of groups) lines.push(`  ${g},`);
  lines.push('} as const;');
  lines.push('');
  return lines.join('\n');
}

function write(target, contents) {
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.writeFileSync(target, contents, 'utf8');
  console.log(`  generated ${path.relative(ROOT, target)}`);
}

function main() {
  const raw = fs.readFileSync(SOURCE, 'utf8');
  const data = JSON.parse(raw);
  decimalKeys = findDecimalKeys(raw);
  console.log(`codegen from ${path.relative(ROOT, SOURCE)}:`);
  write(CS_OUT, generateCSharp(data));
  write(TS_OUT, generateTypeScript(data));
}

main();
